Update fetch-release.yml

diff --git a/.github/workflows/fetch-release.yml b/.github/workflows/fetch-release.yml
--- a/.github/workflows/fetch-release.yml
+++ b/.github/workflows/fetch-release.yml
@@ -57,13 +57,28 @@ jobs:
           echo "Commit tag for DevOps repo: $COMMIT_DEVOPS_TAG"
           echo "IS_DEVOPS_TAG_BY_COMMIT value: $IS_DEVOPS_TAG_BY_COMMIT"
 
+          if [[ "$IS_DEVOPS_TAG_BY_COMMIT" == "TRUE" ]]
+          then
+               COMMIT_DEVOPS_TAG_VERSION=$COMMIT_DEVOPS_TAG
+          elif [[ "$IS_DEVOPS_TAG_BY_COMMIT" == "FALSE" ]]
+               COMMIT_DEVOPS_TAG_VERSION=${{ vars.DEVOPS_VERSION }}
+          else
+               echo -e "\e[1;31m DevOps Release Tag found invalid. \e[0m"
+               exit 1
+          fi
+
+          echo COMMIT_DEVOPS_TAG_VERSION value: $COMMIT_DEVOPS_TAG_VERSION
+          echo "COMMIT_DEVOPS_TAG_VERSION=$COMMIT_DEVOPS_TAG_VERSION" >> $GITHUB_ENV
+
       - name: Tag value validation checkpoint
         run: |
 
-          if [ $(curl -LI -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_SECRET }}" -H "X-GitHub-Api-Version: 2022-11-28" -o /dev/null -w '%{http_code}\n' -s https://api.github.com/repos/cloudspikes-inc/child-repo-trigger/git/trees/${{ vars.DEVOPS_VERSION }}) == "200" ]; then
-            echo -e "\e[1;32m ${{ vars.DEVOPS_VERSION }} DevOps Version tag exists. \e[0m"
+          echo COMMIT_DEVOPS_TAG_VERSION value: $COMMIT_DEVOPS_TAG_VERSION
+
+          if [ $(curl -LI -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT_SECRET }}" -H "X-GitHub-Api-Version: 2022-11-28" -o /dev/null -w '%{http_code}\n' -s https://api.github.com/repos/cloudspikes-inc/child-repo-trigger/git/trees/$COMMIT_DEVOPS_TAG_VERSION) == "200" ]; then
+            echo -e "\e[1;32m $COMMIT_DEVOPS_TAG_VERSION DevOps Version tag exists. \e[0m"
           else
-            echo -e "\e[1;31m ${{ vars.DEVOPS_VERSION }} is not a valid release or tag. \e[0m"
+            echo -e "\e[1;31m $COMMIT_DEVOPS_TAG_VERSION is not a valid release or tag. \e[0m"
             exit 1
           fi
 
