Update fetch-release.yml

diff --git a/.github/workflows/fetch-release.yml b/.github/workflows/fetch-release.yml
--- a/.github/workflows/fetch-release.yml
+++ b/.github/workflows/fetch-release.yml
@@ -57,14 +57,13 @@ jobs:
           echo "Commit tag for DevOps repo: $COMMIT_DEVOPS_TAG"
           echo "IS_DEVOPS_TAG_BY_COMMIT value: $IS_DEVOPS_TAG_BY_COMMIT"
 
-          if [[ "$IS_DEVOPS_TAG_BY_COMMIT" == "TRUE" ]]
-          then
-               COMMIT_DEVOPS_TAG_VERSION=$COMMIT_DEVOPS_TAG
+          if [[ "$IS_DEVOPS_TAG_BY_COMMIT" == "TRUE" ]]; then
+            COMMIT_DEVOPS_TAG_VERSION=$COMMIT_DEVOPS_TAG
           elif [[ "$IS_DEVOPS_TAG_BY_COMMIT" == "FALSE" ]]
-               COMMIT_DEVOPS_TAG_VERSION=${{ vars.DEVOPS_VERSION }}
+             COMMIT_DEVOPS_TAG_VERSION=${{ vars.DEVOPS_VERSION }}
           else
-               echo -e "\e[1;31m DevOps Release Tag found invalid. \e[0m"
-               exit 1
+             echo -e "\e[1;31m DevOps Release Tag found invalid. \e[0m"
+             exit 1
           fi
 
           echo COMMIT_DEVOPS_TAG_VERSION value: $COMMIT_DEVOPS_TAG_VERSION
